name: DB Upgrade

on:
  workflow_dispatch:

concurrency:
  group: deploy-lock
  cancel-in-progress: false

jobs:
  db-upgrade:
    runs-on: ubuntu-latest
    environment: db_upgrade
    steps:
      - name: Start DB upgrade
        run: echo "DB upgrade running..."

      - name: Simulate long DB upgrade
        run: sleep 300   # 5 minutes

      - name: Finish DB upgrade
        run: echo "DB upgrade completed"
